version: "3"

services:
  # https://www.mysql.com/
  db:
    container_name: ows-database
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db/my.cnf:/etc/mysql/my.cnf
      - ows-database:/var/lib/mysql
    networks:
      - internal
      - ows-phpmyadmin

  # https://www.phpmyadmin.net/
  phpmyadmin:
    container_name: ows-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    tty: true
    ports:
      - ${PORT_DB}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 25M
    networks:
      - ows-phpmyadmin

  # https://www.php.net/
  php:
    container_name: ows-php
    depends_on:
      - db
    build:
      context: .
      dockerfile: php/Dockerfile
    restart: always
    tty: true
    working_dir: /var/www/src
    volumes:
      - ../:/var/www/src
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - internal

  # https://getcomposer.org/
  composer:
    depends_on:
      - php
    container_name: ows-composer
    build:
      context: .
      dockerfile: composer/Dockerfile
    working_dir: /var/www/src
    command: "composer install"
    restart: no
    volumes:
      - ../:/var/www/src

  # https://nginx.org/
  nginx:
    container_name: ows-nginx
    depends_on:
      - composer
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    tty: true
    ports:
      - ${PORT_WEBSITE}:3000
      - ${PORT_ADMIN}:3001
    volumes:
      - ../:/var/www/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

networks:
  ows-phpmyadmin:
  internal:
    driver: bridge

volumes:
  ows-database:
