version: "3"

services:
  # https://www.mysql.com/
  db:
    container_name: database
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db/my.cnf:/etc/mysql/my.cnf
      - database:/var/lib/mysql
    networks:
      - internal
      - mysql-phpmyadmin

  # https://www.phpmyadmin.net/
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: unless-stopped
    tty: true
    ports:
      - "3002:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 25M
    networks:
      - mysql-phpmyadmin

  # https://www.php.net/
  php:
    container_name: php
    depends_on:
      - db
    build:
      context: .
      dockerfile: php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/src
    volumes:
      - ../:/var/www/src
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - internal

  # https://getcomposer.org/
  composer:
    depends_on:
      - php
    container_name: composer
    build:
      context: .
      dockerfile: composer/Dockerfile
    working_dir: /var/www/src
    command: "composer install"
    restart: "no"
    volumes:
      - ../:/var/www/src

  # https://nginx.org/
  nginx:
    container_name: nginx
    depends_on:
      - composer
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../:/var/www/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

networks:
  mysql-phpmyadmin:
  internal:
    driver: bridge

volumes:
  database:
